import type { Metadata } from "next";
import { Kanit, Skranji } from "next/font/google";
import "./globals.css";
import { FaMoneyBillWaveAlt, FaShoppingCart } from "react-icons/fa";
import { ModalMoedas } from "@/components/ModalMoedas/modalMoedas";

const kanitRegular = Kanit({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-kanit-regular",
});

// Fonte Kanit com peso maior para os títulos
const skranjiBold = Skranji({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-skranji-bold",
});

export const metadata: Metadata = {
  title: "Reino de Valthorne",

  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body
        className={`${kanitRegular.className} ${skranjiBold.variable} antialiased`}
      >
        <div className="flex gap-4 absolute top-5 right-5">
          <button className="bg-amber-700 px-4 py-2 rounded flex gap-4 font-bold"><FaMoneyBillWaveAlt fontSize={24} /> 50 </button>
          <button className=" bg-amber-700 px-4 py-2 rounded flex gap-4 font-bold"><FaShoppingCart fontSize={24} /> 2 </button>
        </div>
        {children}
      </body>
    </html>
  );
}
