import type { Metadata } from "next";
import { Newsreader } from "next/font/google";
import "./globals.css";
import { LanguageProvider } from "@/context/languageContext";
import { BackgroundAudio } from "@/components/BackgroundAudio/BackgroundAudio";

const newsreader = Newsreader({
  subsets: ["latin"],
  weight: ["400", "700", "600", "800"],
  variable: "--font-newsreader",
});

export const metadata: Metadata = {
  title: "Província do Mercador",

  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={`${newsreader.variable} antialiased`}>
        <BackgroundAudio src="audio/landingBackground.mp3" />
        <LanguageProvider>{children}</LanguageProvider>
      </body>
    </html>
  );
}
